In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df=pd.read_csv(r"C:\Users\USER\Downloads\IMDB Dataset.csv")

In [3]:
print(df.head(2))

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB
None

In [5]:
print(df.isnull().sum())

review       0
sentiment    0
dtype: int64

In [6]:
print(df.duplicated().sum())

418

In [7]:
df.drop_duplicates(keep="first")

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [32]:
print(df['new_sent'].value_counts())

new_sent
1    25000
0    25000
Name: count, dtype: int64

In [8]:
import sys
print(sys.executable)
# It shows which Python interpreter your notebook is currently using.
# sometime lib not happen properly use this path then install
# ->path -m pip install lib

c:\Users\USER\OneDrive\Desktop\Python\fashion\myenv\Scripts\python.exe

In [9]:
import spacy

In [10]:
nlp=spacy.load("en_core_web_sm")

In [11]:
doc=nlp(df["sentiment"].iloc[0])

In [12]:
def preprocess(text):
    text=text.lower()

    text=re.sub(r'<.*?>','',text)
    
    doc=nlp(text)

    clean=[]

    for token in doc:
        if  token.is_punct or  token.is_space:
            continue
        
        if token.is_stop and token.text not in ["not", "no", "never"]:
            continue

        clean.append(token.lemma_)
    
    clean_string=" ".join(clean)

    clean_string=clean_string.strip()

    return clean_string

In [13]:
df['new_sent']=df['sentiment'].map({
    'positive':1,
    'negative':0
})

In [14]:
df["CleanReviw"]=df['review'].apply(lambda x:preprocess(x))

In [15]:
df['CleanReviw'].iloc[0:3]

0    reviewer mention watch 1 oz episode hook right...
1    wonderful little production filming technique ...
2    think wonderful way spend time hot summer week...
Name: CleanReviw, dtype: object

In [16]:
# import gensim.downloader as api
# by this i can download pretrain model of gensim

In [17]:
from gensim.models import Word2Vec

In [18]:
token=df['CleanReviw'].apply(lambda x:x.split())
# it req for word2vec by gensim

In [19]:
vec = Word2Vec(
    sentences=token,
    vector_size=300,
    window=5,
    min_count=1,
    workers=4
)

In [20]:
def makevec(text):
    vector=[]
    words=text.split()

    for word in words:
      if word in vec.wv:
        # wv word vector
        vector.append(vec.wv[word])
    
    if len(vector)==0:
       return np.zeros(vec.vector_size)
    
    else:
       return np.mean(vector,axis=0)


# THIS MANUAL DESIGN FUNCTION

In [21]:
def getvec(text):
    words=text.split()

    return vec.wv.get_mean_vector(words)

# this done by auto

PROBLEM WITH WORDTOVEC THIS CAN'T HENDLE OUT OF VOCAB WORD THAT'S THE MAJOR ISSUE

In [22]:
df['word2vec']=df['CleanReviw'].apply(makevec)

In [23]:
df['word2vec'].iloc[:3]

0    [0.029516561, 0.60485476, 0.100154966, -0.1521...
1    [0.06568278, 0.39472598, 0.0020113115, -0.4017...
2    [0.051158506, 0.41340637, 0.23477304, -0.34433...
Name: word2vec, dtype: object

PROBLEM OF OUT OF VOCAB SOLVE BY FASTTEXT

Word2Vec learns embeddings only for complete words present in the training vocabulary, which creates the Out Of Vocabulary (OOV) problem for unseen or misspelled words. FastText overcomes this limitation by learning character-level subword embeddings. Because FastText understands smaller parts of words, it can generate vectors even for unknown or rare words. This makes FastText more robust and often more effective for real-world text data such as reviews, social media posts, and sentiment analysis tasks.

In [24]:
import fasttext

In [25]:
# fast text also has pre trained model we can also directly import that fasttext.load()
# object.get_word_vector(word)

For training FastText on our own dataset and creating embeddings for our custom text data, the official FastText library does not directly work with pandas columns, dataframes, or Python lists. It expects the training data in the form of a text file where each line represents one sentence or review. Therefore, before training the model, we first save the cleaned text data into a .txt file and then provide that file to the FastText training function.

In [26]:
df['CleanReviw'].to_csv("review.txt",
                    index=False,
                    header=False    
                        )

In [27]:
model=fasttext.train_unsupervised(
    "review.txt" ,
     model='skipgram',
     dim=300
)

In [30]:
model.save_model("embeddingModel.bin")
# bin because fastText internally stores binary data.

In [28]:
def makevec(text):
    vector=[]
    doc=nlp(text)
    for token in doc:
        vector.append(model.get_word_vector(token.text))
    
    return np.mean(vector,axis=0)

In [31]:
df['fastvec']=df['CleanReviw'].apply(makevec)

KeyboardInterrupt:

In [ ]:
df['fastvec'].iloc[0].shape

(300,)

In [ ]:
df

,review,sentiment,new_sent,CleanReviw,word2vec,fastvec
0,One of the other reviewers has mentioned that ...,positive,1,reviewer mention watch 1 oz episode hook right...,"[-0.026699426, 0.457719, 0.056248873, -0.15962...","[-0.03584729, -0.072228484, -0.035713624, -0.1..."
1,A wonderful little production. <br /><br />The...,positive,1,wonderful little production filming technique ...,"[0.0033222826, 0.3704268, 0.046833597, -0.4067...","[-0.0066883173, -0.07709535, -0.012734795, -0...."
2,I thought this was a wonderful way to spend ti...,positive,1,think wonderful way spend time hot summer week...,"[0.034489926, 0.36251265, 0.20206617, -0.38841...","[-0.01983388, -0.087059036, 0.025548121, -0.18..."
3,Basically there's a family where a little boy ...,negative,0,basically family little boy jake think zombie ...,"[-0.08764966, 0.41330588, 0.09767992, -0.40986...","[-0.058101222, -0.0809275, 0.023560697, -0.155..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1,petter mattei love time money visually stunnin...,"[0.09053255, 0.37841687, 0.14862064, -0.409492...","[-0.020965979, -0.03894619, -0.00081404706, -0..."
...,...,...,...,...,...,...
49995,I thought this movie did a down right good job...,positive,1,think movie right good job creative original e...,"[-0.10281654, 0.24571796, 0.12336803, -0.52412...","[-0.055000912, -0.07964227, 0.0059318366, -0.2..."
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,0,bad plot bad dialogue bad acting idiotic direc...,"[-0.009588385, 0.14800201, 0.0387686, -0.31179...","[-0.03907632, -0.084842786, -0.0104280375, -0...."
49997,I am a Catholic taught in parochial elementary...,negative,0,catholic teach parochial elementary school nun...,"[0.06726641, 0.59463215, 0.17383334, -0.293474...","[-0.037094742, 0.02060916, -0.039100826, -0.17..."
49998,I'm going to have to disagree with the previou...,negative,0,go disagree previous comment maltin second rat...,"[0.037347194, 0.38640636, 0.043965325, -0.2424...","[0.0024010646, -0.040684387, -0.024939364, -0...."
49999,No one expects the Star Trek movies to be high...,negative,0,no expect star trek movie high art fan expect ...,"[-0.12890026, 0.16456544, 0.094725005, -0.4929...","[0.009901432, -0.058824003, 0.025579678, -0.21..."

In [ ]:
import sklearn

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df['fastvec'],df['new_sent'],test_size=0.2,random_state=42,stratify=df['new_sent'])

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras  import layers

In [ ]:
dlmodel=Sequential(
    [
        layers.Dense(128,activation='relu',input_shape=(300,)),
        layers.BatchNormalization(),
        layers.Dropout(0.4),
        layers.Dense(64,activation='relu'),
        layers.BatchNormalization(),
        layers.Dropout(0.3),
        layers.Dense(32,activation='relu'),
        layers.BatchNormalization(),
        layers.Dropout(0.25),
        layers.Dense(1,activation='sigmoid'),
        
    ]
)

c:\Users\USER\OneDrive\Desktop\Python\fashion\myenv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
dlmodel.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy'],

)

In [ ]:
X_train.dtypes

dtype('O')

In [ ]:
print(type(X_train.iloc[0]))  #each row  is one vector 
print(X_train.iloc[0])

<class 'numpy.ndarray'>
[-2.69520888e-03 -2.82191020e-02  3.46727706e-02 -1.84085235e-01
  7.67316595e-02 -2.41399426e-02  1.44793838e-01  2.62031984e-02
  9.95901413e-03  3.55569869e-02 -4.82561179e-02  2.80970111e-02
  5.58379143e-02 -6.03941791e-02 -1.21039394e-02 -5.71627542e-02
 -2.83049475e-02 -3.68165523e-02 -1.98469702e-02 -6.81091323e-02
 -2.38628939e-01 -6.56989068e-02  1.00552954e-01 -4.50814515e-02
 -8.65867808e-02 -4.17422540e-02 -4.61335778e-02 -1.08987071e-01
  5.79239018e-02 -1.28258571e-01 -1.74804598e-01  1.25698403e-01
 -1.18246958e-01 -1.65004339e-02  1.73392135e-03 -5.63416108e-02
 -6.04676045e-02 -9.98339709e-03 -4.38001417e-02 -8.53305012e-02
  6.39385486e-04  2.92683374e-02  3.37645039e-03 -2.17294022e-02
  1.23975933e-01  9.79449973e-02  6.95192665e-02  7.23599270e-02
  1.47441775e-01  2.33530909e-01 -8.44099671e-02 -1.08308196e-02
 -8.71825293e-02 -1.77887842e-01  9.44899768e-03 -1.44717380e-01
 -2.51691714e-02 -3.78146097e-02  1.77237839e-01  1.06712341e-01
  1.82654138e-03  2.09073462e-02  1.83484051e-02 -2.30128542e-02
  1.17712803e-01  2.75608823e-02  8.28002021e-02 -1.88539289e-02
 -8.07590187e-02 -1.67646185e-01 -6.69394583e-02  1.64347857e-01
 -3.97813227e-03 -1.92958996e-01  5.78649691e-04 -2.91567086e-03
 -7.61336461e-02  2.05895435e-02 -1.02755859e-01  1.64629996e-01
 -7.42905727e-03  9.44890380e-02 -8.07804763e-02 -1.60976514e-01
  1.52432531e-01 -1.96123645e-01  9.43371933e-03  5.46648279e-02
 -4.56524715e-02 -3.45836058e-02  5.11952899e-02 -1.17712608e-02
 -2.92620459e-03 -3.64568718e-02 -4.33131009e-02 -4.06389274e-02
 -7.00691119e-02 -1.36523517e-02 -5.31587377e-02 -1.02584779e-01
 -5.69806658e-02 -1.75183609e-01 -3.41171511e-02 -7.04638883e-02
  4.86869784e-03 -8.52406025e-02 -1.24896675e-01 -7.97573011e-03
 -1.47655502e-01  4.86817509e-02  1.15633637e-01 -5.17368503e-02
 -7.20456913e-02 -7.41512030e-02  9.05487537e-02 -8.38055536e-02
  8.74323472e-02 -1.19606659e-01  1.73361357e-02 -8.68871883e-02
 -1.86505122e-03 -1.41568497e-01 -1.26087889e-01  7.49222562e-02
  8.93983841e-02 -2.62300014e-01  9.64896847e-03 -2.70801354e-02
 -1.10295666e-02  3.66936661e-02 -8.30287412e-02  7.20998421e-02
  1.32637754e-01  6.68401718e-02  9.60358605e-02 -2.76210275e-03
  4.36680354e-02 -1.11414269e-02 -3.50888669e-02  1.05477571e-01
  2.84061618e-02 -2.67696176e-02  7.97673464e-02 -2.16990653e-02
  1.56085296e-02 -5.96698094e-03 -1.46039233e-01  1.35332644e-01
  1.50299193e-02 -1.70950577e-01  7.43718632e-03  9.59646106e-02
  2.72845495e-02  1.17396355e-01 -1.53987110e-01 -4.05763499e-02
 -3.06553068e-03 -1.12515181e-01 -6.08451571e-03  1.51633039e-01
  6.48494214e-02  3.65593396e-02  2.91612111e-02  1.36105686e-01
 -1.82526384e-03 -2.21212003e-02  8.67471024e-02  1.37301475e-01
 -5.12418561e-02 -6.20199330e-02  9.28613171e-02  3.44004994e-03
  6.44365475e-02  8.62641931e-02  6.65367255e-03  5.82844876e-02
  2.15543099e-02 -5.03496416e-02 -2.86887381e-02 -3.50949056e-02
 -7.54782856e-02  8.83990619e-03  1.34237334e-01  3.09654996e-02
  6.04888983e-02  1.27906561e-01 -1.98600143e-02  1.14124626e-01
 -9.29522514e-02 -2.13827798e-03  8.67736936e-02  6.88827559e-02
  5.20766489e-02  7.30356127e-02 -2.18099868e-03 -6.35130331e-02
 -1.49346307e-01 -6.28969669e-02 -2.98425909e-02  1.02427110e-01
 -4.59993398e-03 -4.79935557e-02 -1.89216975e-02  9.12107006e-02
 -8.18345398e-02 -3.03083919e-02  3.21665667e-02 -1.01124607e-01
 -1.03626877e-01 -9.65311155e-02  6.33833110e-02  5.21897674e-02
 -1.23327591e-01  1.78499714e-01 -6.29984736e-02  1.38088297e-02
  9.66511965e-02 -1.98898792e-01 -6.71190908e-03  1.38956487e-01
 -5.00639677e-02  4.81226072e-02 -5.22611476e-02 -1.59843430e-01
 -1.50926057e-02 -9.70349833e-02  8.27813298e-02  1.14474937e-01
 -7.98033737e-03  9.32928845e-02 -4.19772379e-02  4.07664068e-02
  1.66349448e-02  1.72931217e-02 -1.22164920e-01 -3.56014632e-02
 -8.87377094e-03  1.44463792e-01 -2.12433543e-02  2.23472323e-02
  1.05647929e-01 -1.15674928e-01 -2.32227575e-02 -1.04233816e-01
  6.11237399e-02 -1.20146926e-02  1.91707145e-02  7.93821439e-02
 -5.30081391e-02  2.49953493e-02 -1.33124933e-01  8.60893428e-02
  1.25395104e-01  2.96471231e-02  2.05825474e-02 -7.04732463e-02
 -5.41844144e-02 -5.20940907e-02  5.89713342e-02  1.32735252e-01
 -2.28017792e-02 -5.43039069e-02 -1.70070009e-04  1.89872235e-02
  8.11920837e-02  2.52128728e-02  2.77497917e-02  2.68725753e-02
 -2.87780408e-02  6.91592991e-02 -2.10043147e-01  2.63919886e-02
  9.52355787e-02 -1.22465059e-01  4.36330438e-02  1.26996443e-01
 -6.79786429e-02 -5.25754504e-02 -1.93341859e-02  1.87115557e-02
 -3.11515760e-02  3.96798775e-02 -9.96345002e-03 -2.85063460e-02
 -1.48729652e-01  2.54395679e-02 -7.00646937e-02 -1.50849149e-01
 -3.26377936e-02  1.56176805e-01  8.11606869e-02  7.98092503e-03
  8.68557021e-02 -5.78729399e-02 -7.60554001e-02  5.29945642e-02
 -9.62428227e-02  2.70048734e-02 -1.26478141e-02 -2.86384989e-02]

In [ ]:
x_train = np.vstack(X_train).astype(np.float32)
x_test = np.vstack(X_test).astype(np.float32)

y_train = np.array(y_train, dtype=np.float32)
y_test = np.array(y_test, dtype=np.float32)

# Each row is an independent NumPy vector.
# But deep learning models expect one single 2D matrix:

In [ ]:
dlmodel.fit(x_train,y_train,epochs=60,batch_size=32)

Epoch 1/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8345 - loss: 0.3754
Epoch 2/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8622 - loss: 0.3302
Epoch 3/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8643 - loss: 0.3252
Epoch 4/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8639 - loss: 0.3240
Epoch 5/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8674 - loss: 0.3163
Epoch 6/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8633 - loss: 0.3217
Epoch 7/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8650 - loss: 0.3229
Epoch 8/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8648 - loss: 0.3214
Epoch 9/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8668 - loss: 0.3196
Epoch 10/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8666 - loss: 0.3158
Epoch 11/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8706 - loss: 0.3156
Epoch 12/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8727 - loss: 0.3132
Epoch 13/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8683 - loss: 0.3144
Epoch 14/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8684 - loss: 0.3167
Epoch 15/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8688 - loss: 0.3153
Epoch 16/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8690 - loss: 0.3154
Epoch 17/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8694 - loss: 0.3177
Epoch 18/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8694 - loss: 0.3153
Epoch 19/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8721 - loss: 0.3144
Epoch 20/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8710 - loss: 0.3140
Epoch 21/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8666 - loss: 0.3232
Epoch 22/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8695 - loss: 0.3213
Epoch 23/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8704 - loss: 0.3172
Epoch 24/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8708 - loss: 0.3175
Epoch 25/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8681 - loss: 0.3183
Epoch 26/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8694 - loss: 0.3163
Epoch 27/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8697 - loss: 0.3154
Epoch 28/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8719 - loss: 0.3147
Epoch 29/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8699 - loss: 0.3156
Epoch 30/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8709 - loss: 0.3123
Epoch 31/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8721 - loss: 0.3139
Epoch 32/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8691 - loss: 0.3162
Epoch 33/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8708 - loss: 0.3135
Epoch 34/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8739 - loss: 0.3092
Epoch 35/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8736 - loss: 0.3107
Epoch 36/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8725 - loss: 0.3107
Epoch 37/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8729 - loss: 0.3106
Epoch 38/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8726 - loss: 0.3107
Epoch 39/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8735 - loss: 0.3098
Epoch 40/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8713 - loss: 0.3098
Epoch 41/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8715 - loss: 0.3098
Epoch 42/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8744 - loss: 0.3080
Epoch 43/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8716 - loss: 0.3105
Epoch 44/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8751 - loss: 0.3063
Epoch 45/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8753 - loss: 0.3040
Epoch 46/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8747 - loss: 0.3045
Epoch 47/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8723 - loss: 0.3109
Epoch 48/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8751 - loss: 0.3064
Epoch 49/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8746 - loss: 0.3077
Epoch 50/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8744 - loss: 0.3073
Epoch 51/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8743 - loss: 0.3056
Epoch 52/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8727 - loss: 0.3091
Epoch 53/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8752 - loss: 0.3069
Epoch 54/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8748 - loss: 0.3063
Epoch 55/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8763 - loss: 0.3058
Epoch 56/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8758 - loss: 0.3036
Epoch 57/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8755 - loss: 0.3037
Epoch 58/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8751 - loss: 0.3035
Epoch 59/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8758 - loss: 0.3041
Epoch 60/60
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8761 - loss: 0.3048

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
y_pred=list((dlmodel.predict(x_test)>0.5).astype(int))

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.86      0.91      0.88      4727
           1       0.91      0.86      0.89      5273

    accuracy                           0.88     10000
   macro avg       0.88      0.88      0.88     10000
weighted avg       0.88      0.88      0.88     10000

In [ ]:
print(confusion_matrix(y_pred,y_test))

[[4280  447]
 [ 720 4553]]

In [ ]:
# dlmodel.save("ReviewAnalyiser.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.